
SOCIAL_BADGE_MAP = {
                        "LinkedIn": ("0077B5", "linkedin"),
                        "Twitter": ("1DA1F2", "twitter"),
                        "X": ("000000", "x"),
                        "YouTube": ("FF0000", "youtube"),
                        "Instagram": ("E4405F", "instagram"),
                        "Dev.to": ("0A0A0A", "devdotto"),
                        "Medium": ("000000", "medium"),
                        "Hashnode": ("2962FF", "hashnode"),
                        "Stack Overflow": ("FE7A16", "stackoverflow"),
                        "Discord": ("5865F2", "discord"),
                        "Telegram": ("26A5E4", "telegram"),
                        "Reddit": ("FF4500", "reddit"),
                        "Twitch": ("9146FF", "twitch"),
                        "CodePen": ("000000", "codepen"),
                        "Dribbble": ("EA4C89", "dribbble"),
                        "Behance": ("1769FF", "behance"),
                        "Portfolio": ("000000", "firefox"),
                        "Blog": ("FF5722", "blogger"),
                        "Email": ("D14836", "gmail"),
                        "Kaggle": ("20BEFF", "kaggle"),
                        "LeetCode": ("FFA116", "leetcode"),
                        "HackerRank": ("2EC866", "hackerrank"),
                        "Codeforces": ("1F8ACB", "codeforces"),
                    }